services:
  - type: web
    name: cu-portal-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker test_login:app
    envVars:
      - key: BOT_TOKEN
        value: "7705015733:AAHfQt0Ar2Y7ECVqMhxk45o4xRg9OhFlunQ"
      - key: PORT
        value: "5000"
      - key: WEBHOOK_URL
        value: "https://cu-portal-bot.onrender.com/webhook"