services:
  - type: web
    name: cu-portal-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5000 test_login:app
    envVars:
      - key: BOT_TOKEN
        value: "7705015733:AAHfQt0Ar2Y7ECVqMhxk45o4xRg9OhFlunQ"
      - key: PORT
        value: "5000"