services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python test_login.py"
    envVars:
      - key: BOT_TOKEN
        value: "YOUR_BOT_TOKEN_HERE"
      - key: PORT
        value: "5000"