services:
  - type: web
    name: cu-portal-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python test_login.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORTAL_USERNAME
        sync: false
      - key: PORTAL_PASSWORD
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: "5000"